// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: c245_lvgl

#include "../ui.h"

void ui_main_screen_init(void)
{
    ui_main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HEAD = lv_obj_create(ui_main);
    lv_obj_set_width(ui_HEAD, 240);
    lv_obj_set_height(ui_HEAD, 24);
    lv_obj_set_x(ui_HEAD, 0);
    lv_obj_set_y(ui_HEAD, -108);
    lv_obj_set_align(ui_HEAD, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HEAD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_runtime = lv_label_create(ui_HEAD);
    lv_obj_set_width(ui_runtime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_runtime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_runtime, -45);
    lv_obj_set_y(ui_runtime, 0);
    lv_obj_set_align(ui_runtime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_runtime, "已运行99时99分");
    lv_obj_set_style_text_font(ui_runtime, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_status = lv_label_create(ui_HEAD);
    lv_obj_set_width(ui_status, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_status, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_status, 95);
    lv_obj_set_y(ui_status, 0);
    lv_obj_set_align(ui_status, LV_ALIGN_CENTER);
    lv_label_set_text(ui_status, "休眠");
    lv_obj_set_style_text_font(ui_status, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sound = lv_img_create(ui_HEAD);
    lv_img_set_src(ui_sound, &ui_img_img_heart_big_png);
    lv_obj_set_width(ui_sound, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sound, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sound, 52);
    lv_obj_set_y(ui_sound, 1);
    lv_obj_set_align(ui_sound, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sound, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sound, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mainpanel = lv_obj_create(ui_main);
    lv_obj_set_width(ui_mainpanel, 240);
    lv_obj_set_height(ui_mainpanel, 216);
    lv_obj_set_x(ui_mainpanel, 0);
    lv_obj_set_y(ui_mainpanel, 12);
    lv_obj_set_align(ui_mainpanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_mainpanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_temperature = lv_label_create(ui_mainpanel);
    lv_obj_set_width(ui_temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperature, 12);
    lv_obj_set_y(ui_temperature, -50);
    lv_obj_set_align(ui_temperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temperature, "999");
    lv_obj_set_style_text_font(ui_temperature, &ui_font_tempnum, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PWMBar = lv_bar_create(ui_mainpanel);
    lv_bar_set_value(ui_PWMBar, 25, LV_ANIM_OFF);
    lv_obj_set_width(ui_PWMBar, 160);
    lv_obj_set_height(ui_PWMBar, 20);
    lv_obj_set_x(ui_PWMBar, -36);
    lv_obj_set_y(ui_PWMBar, 88);
    lv_obj_set_align(ui_PWMBar, LV_ALIGN_CENTER);

    ui_tempstr = lv_label_create(ui_mainpanel);
    lv_obj_set_width(ui_tempstr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempstr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempstr, -105);
    lv_obj_set_y(ui_tempstr, -50);
    lv_obj_set_align(ui_tempstr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempstr, "温\n\n度");
    lv_obj_set_style_text_font(ui_tempstr, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_powerstr = lv_label_create(ui_mainpanel);
    lv_obj_set_width(ui_powerstr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_powerstr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_powerstr, 81);
    lv_obj_set_y(ui_powerstr, 78);
    lv_obj_set_align(ui_powerstr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_powerstr, "功率W");
    lv_obj_set_style_text_font(ui_powerstr, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_powerint = lv_label_create(ui_mainpanel);
    lv_obj_set_width(ui_powerint, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_powerint, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_powerint, 81);
    lv_obj_set_y(ui_powerint, 98);
    lv_obj_set_align(ui_powerint, LV_ALIGN_CENTER);
    lv_label_set_text(ui_powerint, "888.8");
    lv_obj_set_style_text_font(ui_powerint, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_targettempstr = lv_label_create(ui_mainpanel);
    lv_obj_set_width(ui_targettempstr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_targettempstr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_targettempstr, -105);
    lv_obj_set_y(ui_targettempstr, 33);
    lv_obj_set_align(ui_targettempstr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_targettempstr, "目\n标");
    lv_obj_set_style_text_font(ui_targettempstr, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_targettempval = lv_label_create(ui_mainpanel);
    lv_obj_set_width(ui_targettempval, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_targettempval, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_targettempval, -40);
    lv_obj_set_y(ui_targettempval, 31);
    lv_obj_set_align(ui_targettempval, LV_ALIGN_CENTER);
    lv_label_set_text(ui_targettempval, "999");
    lv_obj_set_style_text_font(ui_targettempval, &ui_font_target, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_voltage = lv_label_create(ui_mainpanel);
    lv_obj_set_width(ui_voltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_voltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_voltage, 68);
    lv_obj_set_y(ui_voltage, 44);
    lv_obj_set_align(ui_voltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_voltage, "电流 5.8 A");
    lv_obj_set_style_text_font(ui_voltage, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_electricity = lv_label_create(ui_mainpanel);
    lv_obj_set_width(ui_electricity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_electricity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_electricity, 68);
    lv_obj_set_y(ui_electricity, 21);
    lv_obj_set_align(ui_electricity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_electricity, "电压24.0V");
    lv_obj_set_style_text_font(ui_electricity, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

}
