// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: c245_lvgl

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_main
void ui_main_screen_init(void);
lv_obj_t * ui_main;
lv_obj_t * ui_HEAD;
lv_obj_t * ui_runtime;
lv_obj_t * ui_status;
lv_obj_t * ui_sound;
lv_obj_t * ui_mainpanel;
lv_obj_t * ui_temperature;
lv_obj_t * ui_PWMBar;
lv_obj_t * ui_tempstr;
lv_obj_t * ui_powerstr;
lv_obj_t * ui_powerint;
lv_obj_t * ui_targettempstr;
lv_obj_t * ui_targettempval;
lv_obj_t * ui_voltage;
lv_obj_t * ui_electricity;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_main_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_main);
}
