// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: c245_lvgl

#ifndef _C245_LVGL_UI_H
#define _C245_LVGL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_main
void ui_main_screen_init(void);
extern lv_obj_t * ui_main;
extern lv_obj_t * ui_HEAD;
extern lv_obj_t * ui_runtime;
extern lv_obj_t * ui_status;
extern lv_obj_t * ui_sound;
extern lv_obj_t * ui_mainpanel;
extern lv_obj_t * ui_temperature;
extern lv_obj_t * ui_PWMBar;
extern lv_obj_t * ui_tempstr;
extern lv_obj_t * ui_powerstr;
extern lv_obj_t * ui_powerint;
extern lv_obj_t * ui_targettempstr;
extern lv_obj_t * ui_targettempval;
extern lv_obj_t * ui_voltage;
extern lv_obj_t * ui_electricity;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_img_heart_big_png);    // assets\img_heart_big.png

LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_target);
LV_FONT_DECLARE(ui_font_tempnum);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
